### ISSUE TITLE
The equal sign is wider than other binary operators

### ISSUE THREAD

**Issue by xsrvmy** [stipub/stixfonts#157]
I have yet to confirm this locally, but using the version on stix2 on Overleaf, the output of

```
\newlength\mathwidth
\setlength\mathwidth{\widthof{$a=b$}}
\the\mathwidth

\setlength\mathwidth{\widthof{$a\subset b$}}
\the\mathwidth

\setlength\mathwidth{\widthof{$a\subseteq b$}}
\the\mathwidth

\setlength\mathwidth{\widthof{$a<b$}}
\the\mathwidth

\setlength\mathwidth{\widthof{$a\le b$}}
\the\mathwidth
```

is 

23.48602pt
23.29602pt
23.29602pt
23.29602pt
23.29602pt

indicating that the equal sign is too wide. This affects the alignment of the AMS align environment.

**Comment by xsrvmy** [comment]
Just opened a local copy of the otf file in fontforge. Can confirm this is a problem in version 2.00999. < and > has width 701, while = has width 720.

**Comment by tiroj** [comment]
I believe this is fixed in the most recent round of work we've been completing, but will check and confirm.

**Comment by xsrvmy** [comment]
It seems like this is still an issue in 2.11. Is it going to be fixed soon?

**Comment by tiroj** [comment]
Sorry, because this issue wasn't flagged as a 2.10 work item (it was logged after those items were contracted), it slipped past my review. If we have cause to crack the sources again in the next little while, I will try to remember to address this, but it should definitely get flagged as a new item for the next round of work.

**Comment by tiroj** [comment]
I've checked this again, and I think the issue is actually that some of the other operators are too narrow. 720 units is the common width for most of the operators. The exceptions are /multiply /less /greater, which are narrower.

My thought is that the those three should be made wider to align with the common width. Yes?

**Comment by davidmjones** [comment]
That makes sense to me.  Does this also apply to all of the related characters such as U++2264 LESS-THAN OR EQUAL TO, U+2265 GREATER-THAN OR EQUAL TO,  etc.?

**Comment by tiroj** [comment]
I'll do a check of all the math operators. If their proportions lend themselves to a standard width, then I will make that 720 units (and ensure that the ssty and ssty2 variants are on their own standard widths).

**Comment by tiroj** [comment]
This is going to be a fairly extreme measure, affecting a _lot_ of glyphs in the Math font. The common width of the basic arithmetic operators (plus, minus, equal, etc.) is 720 units, but almost all the other operators have a width of 701 (with corresponding mismatches between widths of ssty and ssty2 variants). I think the best approach will be to standardise all to 720 units, as this means we can retain the proportion and spacing of the most common, and not risk anything getting too cramped.

I will be adding 19 units to the width of all those operators that are currently 701 units (split between left and right sidebearings based on direction of sign).

**Comment by tiroj** [comment]
New default operator width = 720
New ssty operator width = 772
New ssty2 operator width = 800

**Comment by tiroj** [comment]
NOTE: this change for 2.12 currently applied only to Math font. Operators in the Text fonts are already of more varied width. @davidmjones can you review the Regular and Bold text fonts and confirm whether operator widths are okay or should be rationalised as in the Math font?
